### ISSUE TITLE
PyPi Release Behind But??

### ISSUE THREAD

**Issue by JustAShoeMaker** [richardpenman/pywhois#11]
Seems like what is available on PyPi (0.7.1) is months behind this one here which is 0.7.0 but has recent commits? (got here from the PyPi -> Bitbucket -> Migrated Repo Link

And sublt name differance
pywhois (here)
vs python-whois (PyPi)

**Comment by richardpenman** [comment]
whoops, must have been something missed when migrated from bitbucket to github. Have pushed 0.7.2 with latest merges.
