### ISSUE TITLE
Does not support IPv6 addresses

### ISSUE THREAD

**Issue by dfeinzeig** [richardpenman/pywhois#2]
https://github.com/richardpenman/pywhois/blob/master/whois/__init__.py#L22

only supports ipv4

**Comment by richardpenman** [comment]
patch welcome!

**Comment by dfeinzeig** [comment]
👍 will get one ready soon

**Comment by dfeinzeig** [comment]
@richardpenman fixed in PR #12

**Comment by dfeinzeig** [comment]
Thx for merging @richardpenman !

Can you please update pypi when you have a chance?

**Comment by richardpenman** [comment]
sure, have pushed an update:
https://pypi.org/project/python-whois/

Thanks very much for the patch

**Comment by dfeinzeig** [comment]
Thanks and welcome!
