### ISSUE TITLE
com.hk issue

### ISSUE THREAD

**Issue by matandobr** [richardpenman/pywhois#30]
Hey!
Thanks for the library.
I seems like it throws an exception even though it got a good response
![image](https://user-images.githubusercontent.com/6709304/71764225-a941a580-2eed-11ea-912c-72653dac7d81.png)

`<class 'tuple'>: (<class 'whois.parser.PywhoisError'>, PywhoisError(" \n -------------------------------------------------------------------------------\n Whois server by HKIRC\n -------------------------------------------------------------------------------\n .hk top level Domain names can be registered via HKIRC-Accredited Registrars. \n Go to https://www.hkirc.hk/content.jsp?id=280 for details. \n -------------------------------------------------------------------------------\n\n\n\nDomain Name:  GOOGLE.COM.HK \n\nDomain Status: Active \n\nDNSSEC:  unsigned  \n\nContract Version:   Refer to registrar   \n\nActive variants\n\nInactive variants\n\nRegistrar Name: MARKMONITOR INC.\n\nRegistrar Contact Information: Email: ccops@markmonitor.com\n\nReseller: \n\n\nRegistrant Contact Information:\n\nCompany English Name (It should be the same as the registered/corporation name on your Business Register Certificate or relevant documents): HONG KONG INTERNET HOLDING LIMITED\nCompany Chinese name: \nAddress:   \nCountry: Hong Kong (HK)\nEmail:  Redacted for Privacy Purposes \nDomain Name Commencement Date: 14-07-2001\nExpiry Date: 20-11-2020 \nRe-registration Status:  Complete   \n\n\n\nAdministrative Contact Information:\n\nGiven name: \nFamily name: \nCompany name: \nAddress: \nCountry: \nPhone: \nFax: \nEmail:  Redacted for Privacy Purposes \nAccount Name: \n\n\n\nTechnical Contact Information:\n\nGiven name: \nFamily name: \nCompany name: \nAddress: \nCountry: \nPhone: \nFax: \nEmail:  Redacted for Privacy Purposes \n\n\n\nName Servers Information:\n\nNS1.GOOGLE.COM\nNS2.GOOGLE.COM\nNS3.GOOGLE.COM\nNS4.GOOGLE.COM\n\n\n\nStatus Information:\n\nDomain Prohibit Status: \n\nIf you have any doubt on the Registrant Contact Information, please feel free to contact the relevant registrar for details. Please accept and agree that the registrar may pass your contact information to the relevant domain contact therefore the domain contact can decide how they will follow.\n\n\n -------------------------------------------------------------------------------\n The Registry contains ONLY .com.hk, .net.hk, .edu.hk, .org.hk,\n .gov.hk, idv.hk. and .hk $domains.\n -------------------------------------------------------------------------------\n\nWHOIS Terms of Use \nBy using this WHOIS search enquiry service you agree to these terms of use.\nThe data in HKDNR's WHOIS search engine is for information purposes only and HKDNR does not guarantee the accuracy of the data. The data is provided to assist people to obtain information about the registration record of domain names registered by HKDNR. You agree to use the data for lawful purposes only.\n\nYou are not authorised to use high-volume, electronic or automated processes to access, query or harvest data from this WHOIS search enquiry service.\n\nYou agree that you will not and will not allow anyone else to:\n\na.    use the data for mass unsolicited commercial advertising of any sort via any medium including telephone, email or fax; or\n\nb.    enable high volume, automated or electronic processes that apply to HKDNR or its computer systems including the WHOIS search enquiry service; or\n\nc.    without the prior written consent of HKDNR compile, repackage, disseminate, disclose to any third party or use the data for a purpose other than obtaining information about a domain name registration record; or\n\nd.    use such data to derive an economic benefit for yourself.\n\nHKDNR in its sole discretion may terminate your access to the WHOIS search enquiry service (including, without limitation, blocking your IP address) at any time including, without limitation, for excessive use of the WHOIS search enquiry service.\n\nHKDNR may modify these terms of use at any time by publishing the modified terms of use on its website.\n\n\n\n\n\n\n"), <traceback object at 0x000002918DDD3808>)`

**Comment by richardpenman** [comment]
right, an exception is raised when domain is not found

**Comment by MatthiasLohr** [comment]
Just stumbled upon this. I want to use your package to find if a domain is already taken or free. When a parser exception is thrown like this, I have no means to differentiate between "server is sending bullshit" (e.g., due to a bug, network problems, whatever...) or "the domain actually beeing free".

Any idea how to address this?
