### ISSUE TITLE
Make field names more uniform

### ISSUE THREAD

**Issue by RensOliemans** [richardpenman/pywhois#4]
In order to get more consistent results in pywhois, it would be good to have more uniform field names.

The main thing is `registrant_name` vs `registrant`.
Some TLDs parse the Registrant Name as `registrant` and some parse it as `registrant_name`. Instead of having two field names, which do we want to use? I'd like to edit all regex fields so they're consistent.

**Comment by richardpenman** [comment]
sorry missed this - that is a good point. I think should be `registrant_name` since there are multiple registrant related fields.

**Comment by PedroBarcha** [comment]
I've experienced a similar issue with `expiration_date`/`expired` , `creation_date`/`created`  and `updated-date`/`changed` .

Example:
Running:
`print (list(whois.whois("https://www1.folha.uol.com.br")))`
Gave me:
`['domain', 'registrant', 'registrant_id', 'country', 'owner_c', 'admin_c', 'tech_c', 'billing_c', 'nserver', 'nsstat', 'nslastaa', 'saci', 'created', 'expires', 'changed', 'status', 'nic_hdl_br', 'person', 'email']`

By the way, @RensOliemans, I've also seen `registrar` around there:
`print (list(whois.whois("https://gnu.org")))`
Gives:
`['domain_name', 'registrar', 'whois_server', 'referral_url', 'updated_date', 'creation_date', 'expiration_date', 'name_servers', 'status', 'emails', 'dnssec', 'name', 'org', 'address', 'city', 'state', 'zipcode', 'country']`

**Comment by RensOliemans** [comment]
I created a PR (#13) for `registrant_name`, I think it's best that a new issue is made for all different field inconsistencies to keep the PRs easier to understand.
@PedroBarcha I'll create an issue for the `date` fields.
I'm not sure about the `registrar` field since that is usually a company and I think that `registrar` is a better fit than `registrar_name` or something. What are your thoughts?

**Comment by RensOliemans** [comment]
I created a separate issue for the `date` fields, will merge the other changes in one PR probably since they are too small for new issues on their own

**Comment by richardpenman** [comment]
Thanks - merged
